name: push

on:
  push:
    branches-ignore:
      - master
      - renovate/**
    tags:
      - "*"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/common.yml
